name = "mstore"
version = "0.3.0"
license = "Apache-2.0"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2020-2024 Sebastian Ehlert"
description = "Molecular structure store for testing"
keywords = ["computational-chemistry", "testing"]

[dependencies]
[dependencies.mctc-lib]
git = "https://github.com/grimme-lab/mctc-lib"

[[executable]]
name = "mstore-fortranize"
source-dir = "app/fortranize"

[[executable]]
name = "mstore-info"
source-dir = "app/info"
