name = "mstore"
version = "0.1.0"
license = "Apache-2.0"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2020-2021 Sebastian Ehlert"
description = "Molecular structure store for testing"
keywords = ["computational-chemistry", "testing"]

[dependencies]
[dependencies.mctc-lib]
git = "https://github.com/grimme-lab/mctc-lib"
